version: "3.9"

services:
  livekit:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
    volumes:
      - ./livekit.yaml.template:/etc/livekit.yaml.template:ro
      - ./start.sh:/start.sh:ro
    depends_on:
      - redis
    ports:
      - "7880:7880/tcp"
      - "7881:7881/tcp"
      - "50000-60000:50000-60000/udp"
    entrypoint: /bin/bash /start.sh

  redis:
    image: redis:6-alpine
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
